name = "NearestNeighborDescent"
uuid = "dd2c4c9e-a32f-5b2f-b342-08c2f244fce8"
authors = ["Dillon Daudert <dillongdaudert@gmail.com>"]
version = "0.2.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
DataStructures = "0.15"
Distances = "0.8"
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
